apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaski-app  # It's good practice to keep names lowercase and avoid special characters
  labels:
    app: flaski-app
spec:
  replicas: 2  # Number of pods to run
  selector:
    matchLabels:
      app: flaski-app
  template:
    metadata:
      labels:
        app: flaski-app
    spec:
      containers:
      - name: flaski-app
        image: flask-etl-img:latest

        ports:
        - containerPort: 5020  # Port exposed by the Flask app
        env:
        - name: JAVA_HOME
          value: "/usr/lib/jvm/java-11-openjdk-amd64"  # Example for Linux-based containers
